apiVersion: v1
kind: Pod
metadata:
  labels:
    app: merch-build
spec:
  serviceAccountName: jenkins
  restartPolicy: Never
  containers:
  - name: devops
    image: node:20-alpine
    command: ["sleep", "99d"]
    tty: true
    workingDir: /home/jenkins/agent
    env:
    - name: YQ_VERSION
      value: "v4.40.5"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep", "99d"]
    tty: true
    workingDir: /home/jenkins/agent
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1500m"
    volumeMounts:
    - name: nexus-docker-config
      mountPath: /kaniko/.docker
  - name: security
    image: aquasec/trivy:latest
    command: ["sleep", "99d"]
    tty: true
    workingDir: /home/jenkins/agent
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  volumes:
  - name: nexus-docker-config
    secret:
      secretName: nexus-docker-config
